name: TranslateThis

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v3

      - name: Install Composer Dependencies
        working-directory: ./app
        run: composer install --prefer-dist

      - name: Run Tests
        working-directory: ./app
        run: composer run-phpunit

      # name: Build and Push Images
      - run: docker build --target app -t winston1984/php-composer:1.2 -f ./php/Dockerfile .
      - run: docker build -t winston1984/nginx-php:1.0 -f ./nginx/Dockerfile .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push winston1984/php-composer:1.2
      - run: docker push winston1984/nginx-php:1.0